### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by g40matt** [redstreet/beancount_asset_allocation#3]
Hi - I tried to execute 
./asset_allocation.py example.beancount --accounts "Assets:Investments:" --dump-balances-tree

but it failed with below error

Traceback (most recent call last):
  File "./asset_allocation.py", line 4, in <module>
    import argparse,argcomplete,argh
ModuleNotFoundError: No module named 'argcomplete'

Any help/suggestion would be appreciated!

**Comment by g40matt** [comment]
Got it - needed to install the modules.

**Comment by g40matt** [comment]
Any insight into this error -- running with my beancount file

Traceback (most recent call last):
  File "./asset_allocation.py", line 131, in <module>
    main()
  File "./asset_allocation.py", line 127, in main
    parser.dispatch()
  File "/home/pi/.local/lib/python3.6/site-packages/argh/helpers.py", line 55, in dispatch
    return dispatch(self, *args, **kwargs)
  File "/home/pi/.local/lib/python3.6/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/home/pi/.local/lib/python3.6/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/home/pi/.local/lib/python3.6/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "./asset_allocation.py", line 61, in asset_allocation
    if not is_included_account(acc):
  File "./asset_allocation.py", line 48, in is_included_account
    if re.match(pattern, realacc.account):
AttributeError: 'NoneType' object has no attribute 'account'

**Comment by redstreet** [comment]
That means no included accounts found. (Your --accounts <regex> failed to match any account). Try with --accounts "Assets" for example, and then narrow down your pattern from there.

**Comment by redstreet** [comment]
Did that work?

**Comment by g40matt** [comment]
Sure did - I had a typo in the account search so it wasn't returning any accounts initially.

This is a very handy tool! I'm thinking a few wishlist items

1) Option to subtotal by asset type hierarchy (eg. subtotal for equity, subtotal for bond, etc)
2) Ability to set a tax_rate meta on each account to enable calculation of "After tax" value and percent of total (in addition to the currently shown "Before tax" value;
3) Hide investment accounts with zero holdings in the tree
4) Show "Amount" for each holding in the balance tree (eg. 10 AMZN $20,170.00 USD)
5) Extend Fava

**Comment by redstreet** [comment]
Glad it's useful!

1. It's been on my mind too, will do
2. Yes, this was there in the original proposal, I'll get to it soon https://github.com/beancount/fava/issues/947
3. This one is tricky. I use beancount's code to display the tree, so upstream changes might be required. I might not get to this soon.
4. I'll add an option to display amount instead of value (upstream code doesn't support displaying both together)
5. This was in the original proposal, and I'd like it too, but it'll take me a while until I find a chunk of time to figure out how fava plugins work. PRs welcome on this (and anything else).

Thanks for the note!

**Comment by redstreet** [comment]
1. Assets allocations are now subtotaled and displayed hierarchically. See the README.md for an example.

**Comment by redstreet** [comment]
2, 3, 5 are done, BTW. See https://github.com/redstreet/fava-investor
